# 生产环境配置
spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/aiphone?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    com.aiphone: info
    org.springframework.security: warn
